create extension if not exists pgcrypto;

create table if not exists public.businesses (
  id bigint generated by default as identity primary key,
  name text not null,
  subdomain text unique,
  plan text default 'Starter',
  status text default 'Active',
  created_at timestamptz default now()
);

create table if not exists public.branches (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null default 1,
  name text not null,
  address text,
  phone text,
  created_at timestamptz default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null default 1,
  name text not null,
  icon text default 'Utensils',
  created_at timestamptz default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null default 1,
  code text not null,
  name text not null,
  category_id bigint,
  price numeric not null default 0,
  tax numeric default 0,
  gst numeric default 0,
  description text,
  image_path text,
  status text default 'Available',
  created_at timestamptz default now(),
  constraint products_category_fk foreign key (category_id) references public.categories(id) on delete set null
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null default 1,
  name text not null,
  email text not null unique,
  password text not null,
  role text not null default 'Staff',
  status text default 'Active',
  created_at timestamptz default now()
);

create table if not exists public.bills (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null default 1,
  bill_number text not null,
  date timestamptz default now(),
  cashier_name text not null,
  subtotal numeric not null,
  discount numeric default 0,
  tax numeric default 0,
  round_off numeric default 0,
  grand_total numeric not null,
  payment_type text not null default 'Cash',
  status text default 'Paid'
);

create table if not exists public.bill_items (
  id bigint generated by default as identity primary key,
  bill_id bigint references public.bills(id) on delete cascade,
  product_code text not null,
  product_name text not null,
  quantity integer not null,
  rate numeric not null,
  amount numeric not null
);

create table if not exists public.settings (
  key text primary key,
  value text,
  tenant_id bigint not null default 1
);

create table if not exists public.database_info (
  id bigint generated by default as identity primary key,
  version text default '1.0.0',
  last_sync timestamptz
);

insert into public.businesses (id, name, subdomain, plan, status)
values (1, 'SAVORA Bakery & Ice Bay', 'savora', 'Starter', 'Active')
on conflict (id) do nothing;

insert into public.branches (id, tenant_id, name, address, phone)
values (1, 1, 'Beach Road Arcade', 'Shop No 14, Beach Road, Kochi, Kerala', '+91 98765 43210')
on conflict (id) do nothing;
